import { Inter } from "next/font/google";
import "./globals.css";
import 'daisyui/dist/full.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <>

    <html className=" flex items-center h-screen justify-center" data-theme='cupcake'  lang="en">
      <body data-theme='cupcake' className={inter.className}>{children}</body>
    </html>
    </>
  );
}
